FROM cypress/base:10
RUN node --version
RUN npm --version
WORKDIR /home/node/app

COPY cypress.json package.json package-lock.json ./
COPY cypress ./cypress
COPY wait-for-it.sh ./

# avoid many lines of progress bars during install
# https://github.com/cypress-io/cypress/issues/1243
ENV CI=1

# install NPM dependencies and Cypress binary
RUN npm ci

# check if the binary was installed successfully
RUN $(npm bin)/cypress verify
