// flow-typed signature: e92912d86c4b2674eb0cf1197e78a6d3
// flow-typed version: <<STUB>>/apollo-link-state_v^0.4.2/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-state/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-state/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link-state/lib/utils' {
  declare module.exports: any;
}

declare module 'apollo-link-state/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-state/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-state/lib/bundle.umd'>;
}
declare module 'apollo-link-state/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-state/lib/index'>;
}
declare module 'apollo-link-state/lib/utils.js' {
  declare module.exports: $Exports<'apollo-link-state/lib/utils'>;
}
declare module 'apollo-link-state/rollup.config.js' {
  declare module.exports: $Exports<'apollo-link-state/rollup.config'>;
}
