// flow-typed signature: 93bdf0f5f7bd02190cf3bf3a357fe675
// flow-typed version: <<STUB>>/concurrently_v^0.1.1/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'concurrently'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'concurrently' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'concurrently/src/lodash-mixins' {
  declare module.exports: any;
}

declare module 'concurrently/src/main' {
  declare module.exports: any;
}

declare module 'concurrently/test/test-functional' {
  declare module.exports: any;
}

declare module 'concurrently/test/utils' {
  declare module.exports: any;
}

declare module 'concurrently/tools/release' {
  declare module.exports: any;
}

// Filename aliases
declare module 'concurrently/src/lodash-mixins.js' {
  declare module.exports: $Exports<'concurrently/src/lodash-mixins'>;
}
declare module 'concurrently/src/main.js' {
  declare module.exports: $Exports<'concurrently/src/main'>;
}
declare module 'concurrently/test/test-functional.js' {
  declare module.exports: $Exports<'concurrently/test/test-functional'>;
}
declare module 'concurrently/test/utils.js' {
  declare module.exports: $Exports<'concurrently/test/utils'>;
}
declare module 'concurrently/tools/release.js' {
  declare module.exports: $Exports<'concurrently/tools/release'>;
}
