// flow-typed signature: e01c961be5b487a19b0dedae24f72eb6
// flow-typed version: <<STUB>>/webpack-runtime-analyzer_v1.5.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-runtime-analyzer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-runtime-analyzer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-runtime-analyzer/dist/script' {
  declare module.exports: any;
}

declare module 'webpack-runtime-analyzer/src/plugin/index' {
  declare module.exports: any;
}

declare module 'webpack-runtime-analyzer/src/plugin/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-runtime-analyzer/dist/script.js' {
  declare module.exports: $Exports<'webpack-runtime-analyzer/dist/script'>;
}
declare module 'webpack-runtime-analyzer/src/plugin/index.js' {
  declare module.exports: $Exports<'webpack-runtime-analyzer/src/plugin/index'>;
}
declare module 'webpack-runtime-analyzer/src/plugin/server.js' {
  declare module.exports: $Exports<'webpack-runtime-analyzer/src/plugin/server'>;
}
