// flow-typed signature: caaf3defbff6502870c9900cae5da106
// flow-typed version: <<STUB>>/apollo-resolvers_v^1.4.1/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-resolvers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-resolvers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-resolvers/dist/context' {
  declare module.exports: any;
}

declare module 'apollo-resolvers/dist/helper' {
  declare module.exports: any;
}

declare module 'apollo-resolvers/dist/index' {
  declare module.exports: any;
}

declare module 'apollo-resolvers/dist/promise' {
  declare module.exports: any;
}

declare module 'apollo-resolvers/dist/resolver' {
  declare module.exports: any;
}

declare module 'apollo-resolvers/dist/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-resolvers/dist/context.js' {
  declare module.exports: $Exports<'apollo-resolvers/dist/context'>;
}
declare module 'apollo-resolvers/dist/helper.js' {
  declare module.exports: $Exports<'apollo-resolvers/dist/helper'>;
}
declare module 'apollo-resolvers/dist/index.js' {
  declare module.exports: $Exports<'apollo-resolvers/dist/index'>;
}
declare module 'apollo-resolvers/dist/promise.js' {
  declare module.exports: $Exports<'apollo-resolvers/dist/promise'>;
}
declare module 'apollo-resolvers/dist/resolver.js' {
  declare module.exports: $Exports<'apollo-resolvers/dist/resolver'>;
}
declare module 'apollo-resolvers/dist/util.js' {
  declare module.exports: $Exports<'apollo-resolvers/dist/util'>;
}
