// flow-typed signature: 15fe4473a75e3ee36f3a5f23f3a21990
// flow-typed version: <<STUB>>/apollo-errors_v^1.9.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-errors/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-errors/dist/index.js' {
  declare module.exports: $Exports<'apollo-errors/dist/index'>;
}
