// flow-typed signature: 3d1c8c9857c0ddd46052eff9b791cdbb
// flow-typed version: <<STUB>>/optimism_v^0.6.6/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'optimism'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'optimism' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'optimism/lib/cache' {
  declare module.exports: any;
}

declare module 'optimism/lib/entry' {
  declare module.exports: any;
}

declare module 'optimism/lib/index' {
  declare module.exports: any;
}

declare module 'optimism/lib/local' {
  declare module.exports: any;
}

// Filename aliases
declare module 'optimism/lib/cache.js' {
  declare module.exports: $Exports<'optimism/lib/cache'>;
}
declare module 'optimism/lib/entry.js' {
  declare module.exports: $Exports<'optimism/lib/entry'>;
}
declare module 'optimism/lib/index.js' {
  declare module.exports: $Exports<'optimism/lib/index'>;
}
declare module 'optimism/lib/local.js' {
  declare module.exports: $Exports<'optimism/lib/local'>;
}
