// flow-typed signature: 61e2d9176b3b64180ea1247a84d171f8
// flow-typed version: <<STUB>>/string-replace-loader_v1.2.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-replace-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-replace-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'string-replace-loader/index' {
  declare module.exports: $Exports<'string-replace-loader'>;
}
declare module 'string-replace-loader/index.js' {
  declare module.exports: $Exports<'string-replace-loader'>;
}
